package com.ruoyi.mry.mapper;

import com.ruoyi.mry.model.MryCustomerProItem;
import com.ruoyi.mry.model.MryCustomerProItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MryCustomerProItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int countByExample(MryCustomerProItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int deleteByExample(MryCustomerProItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int insert(MryCustomerProItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int insertSelective(MryCustomerProItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    List<MryCustomerProItem> selectByExample(MryCustomerProItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    MryCustomerProItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MryCustomerProItem record, @Param("example") MryCustomerProItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MryCustomerProItem record, @Param("example") MryCustomerProItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MryCustomerProItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MryCustomerProItem record);
}