package com.ruoyi.mry.mapper;

import com.ruoyi.mry.model.MryCustomerPicture;
import com.ruoyi.mry.model.MryCustomerPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MryCustomerPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int countByExample(MryCustomerPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int deleteByExample(MryCustomerPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int insert(MryCustomerPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int insertSelective(MryCustomerPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    List<MryCustomerPicture> selectByExample(MryCustomerPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    MryCustomerPicture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MryCustomerPicture record, @Param("example") MryCustomerPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MryCustomerPicture record, @Param("example") MryCustomerPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MryCustomerPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MryCustomerPicture record);
}