package com.ruoyi.mry.mapper;

import com.ruoyi.mry.model.MryCustomerPro;
import com.ruoyi.mry.model.MryCustomerProExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MryCustomerProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    int countByExample(MryCustomerProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    int deleteByExample(MryCustomerProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    int insert(MryCustomerPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    int insertSelective(MryCustomerPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    List<MryCustomerPro> selectByExample(MryCustomerProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MryCustomerPro record, @Param("example") MryCustomerProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_customer_pro
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MryCustomerPro record, @Param("example") MryCustomerProExample example);
}