package com.ruoyi.mry.mapper;

import com.ruoyi.mry.model.MryStaffLeave;
import com.ruoyi.mry.model.MryStaffLeaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MryStaffLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int countByExample(MryStaffLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int deleteByExample(MryStaffLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int insert(MryStaffLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int insertSelective(MryStaffLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    List<MryStaffLeave> selectByExample(MryStaffLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    MryStaffLeave selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MryStaffLeave record, @Param("example") MryStaffLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MryStaffLeave record, @Param("example") MryStaffLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MryStaffLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_staff_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MryStaffLeave record);
}