package com.ruoyi.mry.mapper;

import com.ruoyi.mry.model.MryWorklog;
import com.ruoyi.mry.model.MryWorklogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MryWorklogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int countByExample(MryWorklogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int deleteByExample(MryWorklogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int insert(MryWorklog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int insertSelective(MryWorklog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    List<MryWorklog> selectByExample(MryWorklogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    MryWorklog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MryWorklog record, @Param("example") MryWorklogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MryWorklog record, @Param("example") MryWorklogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MryWorklog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mry_worklog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MryWorklog record);
}