package com.ruoyi.fac.automapper;

import com.ruoyi.fac.model.FacBusiness;
import com.ruoyi.fac.model.FacBusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    int countByExample(@Param("example") FacBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    int deleteByExample(@Param("example") FacBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    int insert(@Param("record") FacBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    int insertSelective(@Param("record") FacBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    List<FacBusiness> selectByExample(@Param("example") FacBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacBusiness record, @Param("example") FacBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_business
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacBusiness record, @Param("example") FacBusinessExample example);
}