package com.ruoyi.fac.automapper;

import com.ruoyi.fac.model.FacBuyer;
import com.ruoyi.fac.model.FacBuyerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacBuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    int countByExample(@Param("example") FacBuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    int deleteByExample(@Param("example") FacBuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    int insert(@Param("record") FacBuyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    int insertSelective(@Param("record") FacBuyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    List<FacBuyer> selectByExample(@Param("example") FacBuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacBuyer record, @Param("example") FacBuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_buyer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacBuyer record, @Param("example") FacBuyerExample example);
}