package com.ruoyi.fac.automapper;

import com.ruoyi.fac.model.FacCash;
import com.ruoyi.fac.model.FacCashExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacCashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    int countByExample(@Param("example") FacCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    int deleteByExample(@Param("example") FacCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    int insert(@Param("record") FacCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    int insertSelective(@Param("record") FacCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    List<FacCash> selectByExample(@Param("example") FacCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacCash record, @Param("example") FacCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_cash
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacCash record, @Param("example") FacCashExample example);
}