package com.ruoyi.fac.automapper;

import com.ruoyi.fac.model.FacFocusMap;
import com.ruoyi.fac.model.FacFocusMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacFocusMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    int countByExample(@Param("example") FacFocusMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    int deleteByExample(@Param("example") FacFocusMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    int insert(@Param("record") FacFocusMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    int insertSelective(@Param("record") FacFocusMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    List<FacFocusMap> selectByExample(@Param("example") FacFocusMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacFocusMap record, @Param("example") FacFocusMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_focus_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacFocusMap record, @Param("example") FacFocusMapExample example);
}