package com.ruoyi.fac.automapper;

import com.ruoyi.fac.model.FacOrder;
import com.ruoyi.fac.model.FacOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    int countByExample(@Param("example") FacOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    int deleteByExample(@Param("example") FacOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    int insert(@Param("record") FacOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    int insertSelective(@Param("record") FacOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    List<FacOrder> selectByExample(@Param("example") FacOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacOrder record, @Param("example") FacOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacOrder record, @Param("example") FacOrderExample example);
}