package com.ruoyi.fac.automapper;

import com.ruoyi.fac.model.FacProduct;
import com.ruoyi.fac.model.FacProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int countByExample(FacProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int deleteByExample(FacProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int insert(FacProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int insertSelective(FacProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    List<FacProduct> selectByExampleWithBLOBs(FacProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    List<FacProduct> selectByExample(FacProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacProduct record, @Param("example") FacProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") FacProduct record, @Param("example") FacProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacProduct record, @Param("example") FacProductExample example);
}