package com.ruoyi.fac.mapper;

import com.ruoyi.fac.model.FacKanjia;
import com.ruoyi.fac.model.FacKanjiaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacKanjiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    int countByExample(FacKanjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    int deleteByExample(FacKanjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    int insert(FacKanjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    int insertSelective(FacKanjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    List<FacKanjia> selectByExample(FacKanjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacKanjia record, @Param("example") FacKanjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_kanjia
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacKanjia record, @Param("example") FacKanjiaExample example);
}