package com.ruoyi.fac.mapper;

import com.ruoyi.fac.model.FacLeaveMessage;
import com.ruoyi.fac.model.FacLeaveMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacLeaveMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int countByExample(FacLeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int deleteByExample(FacLeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int insert(FacLeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int insertSelective(FacLeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    List<FacLeaveMessage> selectByExample(FacLeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    FacLeaveMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FacLeaveMessage record, @Param("example") FacLeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FacLeaveMessage record, @Param("example") FacLeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FacLeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fac_leave_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FacLeaveMessage record);
}