package com.ruoyi.fac.model;

import java.util.Date;

public class FacBuyerBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.business_id
     *
     * @mbggenerated
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.business_prod_id
     *
     * @mbggenerated
     */
    private Long businessProdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_business.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.id
     *
     * @return the value of fac_buyer_business.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.id
     *
     * @param id the value for fac_buyer_business.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.user_id
     *
     * @return the value of fac_buyer_business.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.user_id
     *
     * @param userId the value for fac_buyer_business.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.token
     *
     * @return the value of fac_buyer_business.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.token
     *
     * @param token the value for fac_buyer_business.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.business_id
     *
     * @return the value of fac_buyer_business.business_id
     *
     * @mbggenerated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.business_id
     *
     * @param businessId the value for fac_buyer_business.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.business_prod_id
     *
     * @return the value of fac_buyer_business.business_prod_id
     *
     * @mbggenerated
     */
    public Long getBusinessProdId() {
        return businessProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.business_prod_id
     *
     * @param businessProdId the value for fac_buyer_business.business_prod_id
     *
     * @mbggenerated
     */
    public void setBusinessProdId(Long businessProdId) {
        this.businessProdId = businessProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.create_time
     *
     * @return the value of fac_buyer_business.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.create_time
     *
     * @param createTime the value for fac_buyer_business.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.update_time
     *
     * @return the value of fac_buyer_business.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.update_time
     *
     * @param updateTime the value for fac_buyer_business.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.operator_id
     *
     * @return the value of fac_buyer_business.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.operator_id
     *
     * @param operatorId the value for fac_buyer_business.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.operator_name
     *
     * @return the value of fac_buyer_business.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.operator_name
     *
     * @param operatorName the value for fac_buyer_business.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_business.is_deleted
     *
     * @return the value of fac_buyer_business.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_business.is_deleted
     *
     * @param isDeleted the value for fac_buyer_business.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}