package com.ruoyi.fac.model;

import java.util.Date;

public class FacBuyerAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.buyer_id
     *
     * @mbggenerated
     */
    private Long buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.provinceId
     *
     * @mbggenerated
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.province_str
     *
     * @mbggenerated
     */
    private String provinceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.cityId
     *
     * @mbggenerated
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.city_str
     *
     * @mbggenerated
     */
    private String cityStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.districtId
     *
     * @mbggenerated
     */
    private Integer districtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.district_str
     *
     * @mbggenerated
     */
    private String districtStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.linkMan
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.is_default
     *
     * @mbggenerated
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer_address.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.id
     *
     * @return the value of fac_buyer_address.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.id
     *
     * @param id the value for fac_buyer_address.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.buyer_id
     *
     * @return the value of fac_buyer_address.buyer_id
     *
     * @mbggenerated
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.buyer_id
     *
     * @param buyerId the value for fac_buyer_address.buyer_id
     *
     * @mbggenerated
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.token
     *
     * @return the value of fac_buyer_address.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.token
     *
     * @param token the value for fac_buyer_address.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.open_id
     *
     * @return the value of fac_buyer_address.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.open_id
     *
     * @param openId the value for fac_buyer_address.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.address
     *
     * @return the value of fac_buyer_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.address
     *
     * @param address the value for fac_buyer_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.provinceId
     *
     * @return the value of fac_buyer_address.provinceId
     *
     * @mbggenerated
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.provinceId
     *
     * @param provinceid the value for fac_buyer_address.provinceId
     *
     * @mbggenerated
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.province_str
     *
     * @return the value of fac_buyer_address.province_str
     *
     * @mbggenerated
     */
    public String getProvinceStr() {
        return provinceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.province_str
     *
     * @param provinceStr the value for fac_buyer_address.province_str
     *
     * @mbggenerated
     */
    public void setProvinceStr(String provinceStr) {
        this.provinceStr = provinceStr == null ? null : provinceStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.cityId
     *
     * @return the value of fac_buyer_address.cityId
     *
     * @mbggenerated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.cityId
     *
     * @param cityid the value for fac_buyer_address.cityId
     *
     * @mbggenerated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.city_str
     *
     * @return the value of fac_buyer_address.city_str
     *
     * @mbggenerated
     */
    public String getCityStr() {
        return cityStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.city_str
     *
     * @param cityStr the value for fac_buyer_address.city_str
     *
     * @mbggenerated
     */
    public void setCityStr(String cityStr) {
        this.cityStr = cityStr == null ? null : cityStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.districtId
     *
     * @return the value of fac_buyer_address.districtId
     *
     * @mbggenerated
     */
    public Integer getDistrictid() {
        return districtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.districtId
     *
     * @param districtid the value for fac_buyer_address.districtId
     *
     * @mbggenerated
     */
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.district_str
     *
     * @return the value of fac_buyer_address.district_str
     *
     * @mbggenerated
     */
    public String getDistrictStr() {
        return districtStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.district_str
     *
     * @param districtStr the value for fac_buyer_address.district_str
     *
     * @mbggenerated
     */
    public void setDistrictStr(String districtStr) {
        this.districtStr = districtStr == null ? null : districtStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.linkMan
     *
     * @return the value of fac_buyer_address.linkMan
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.linkMan
     *
     * @param linkman the value for fac_buyer_address.linkMan
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.phone_number
     *
     * @return the value of fac_buyer_address.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.phone_number
     *
     * @param phoneNumber the value for fac_buyer_address.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.code
     *
     * @return the value of fac_buyer_address.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.code
     *
     * @param code the value for fac_buyer_address.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.is_default
     *
     * @return the value of fac_buyer_address.is_default
     *
     * @mbggenerated
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.is_default
     *
     * @param isDefault the value for fac_buyer_address.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.create_time
     *
     * @return the value of fac_buyer_address.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.create_time
     *
     * @param createTime the value for fac_buyer_address.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.update_time
     *
     * @return the value of fac_buyer_address.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.update_time
     *
     * @param updateTime the value for fac_buyer_address.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.operator_id
     *
     * @return the value of fac_buyer_address.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.operator_id
     *
     * @param operatorId the value for fac_buyer_address.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.operator_name
     *
     * @return the value of fac_buyer_address.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.operator_name
     *
     * @param operatorName the value for fac_buyer_address.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer_address.is_deleted
     *
     * @return the value of fac_buyer_address.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer_address.is_deleted
     *
     * @param isDeleted the value for fac_buyer_address.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}