package com.ruoyi.fac.model;

import com.ruoyi.common.annotation.Excel;

import java.math.BigDecimal;
import java.util.Date;

public class FacKanjiaHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.kanjia_id
     *
     * @mbggenerated
     */
    @Excel(name = "砍价ID")
    private Long kanjiaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.join_id
     *
     * @mbggenerated
     */
    @Excel(name = "砍价活动ID")
    private Long joinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.prod_id
     *
     * @mbggenerated
     */
    @Excel(name = "商品ID")
    private Long prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.prod_name
     *
     * @mbggenerated
     */
    @Excel(name = "商品名称")
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.token_joiner
     *
     * @mbggenerated
     */
    private String tokenJoiner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.nick_name_joiner
     *
     * @mbggenerated
     */
    @Excel(name = "参与用户昵称")
    private String nickNameJoiner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.phone_number_joiner
     *
     * @mbggenerated
     */
    @Excel(name = "参与用户手机号码")
    private String phoneNumberJoiner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.token_helper
     *
     * @mbggenerated
     */
    private String tokenHelper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.nick_name_helper
     *
     * @mbggenerated
     */
    @Excel(name = "助力用户昵称")
    private String nickNameHelper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.phone_number_helper
     *
     * @mbggenerated
     */
    @Excel(name = "助力用户手机号码")
    private String phoneNumberHelper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.help_price
     *
     * @mbggenerated
     */
    @Excel(name = "助力金额")
    private BigDecimal helpPrice;

    /**
     * This field was generated b1y MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.create_time
     *
     * @mbggenerated
     */
    @Excel(name = "砍价时间", dateFormat = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_kanjia_helper.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.id
     *
     * @return the value of fac_kanjia_helper.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.id
     *
     * @param id the value for fac_kanjia_helper.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.kanjia_id
     *
     * @return the value of fac_kanjia_helper.kanjia_id
     * @mbggenerated
     */
    public Long getKanjiaId() {
        return kanjiaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.kanjia_id
     *
     * @param kanjiaId the value for fac_kanjia_helper.kanjia_id
     * @mbggenerated
     */
    public void setKanjiaId(Long kanjiaId) {
        this.kanjiaId = kanjiaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.join_id
     *
     * @return the value of fac_kanjia_helper.join_id
     * @mbggenerated
     */
    public Long getJoinId() {
        return joinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.join_id
     *
     * @param joinId the value for fac_kanjia_helper.join_id
     * @mbggenerated
     */
    public void setJoinId(Long joinId) {
        this.joinId = joinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.prod_id
     *
     * @return the value of fac_kanjia_helper.prod_id
     * @mbggenerated
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.prod_id
     *
     * @param prodId the value for fac_kanjia_helper.prod_id
     * @mbggenerated
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.prod_name
     *
     * @return the value of fac_kanjia_helper.prod_name
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.prod_name
     *
     * @param prodName the value for fac_kanjia_helper.prod_name
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.token_joiner
     *
     * @return the value of fac_kanjia_helper.token_joiner
     * @mbggenerated
     */
    public String getTokenJoiner() {
        return tokenJoiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.token_joiner
     *
     * @param tokenJoiner the value for fac_kanjia_helper.token_joiner
     * @mbggenerated
     */
    public void setTokenJoiner(String tokenJoiner) {
        this.tokenJoiner = tokenJoiner == null ? null : tokenJoiner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.nick_name_joiner
     *
     * @return the value of fac_kanjia_helper.nick_name_joiner
     * @mbggenerated
     */
    public String getNickNameJoiner() {
        return nickNameJoiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.nick_name_joiner
     *
     * @param nickNameJoiner the value for fac_kanjia_helper.nick_name_joiner
     * @mbggenerated
     */
    public void setNickNameJoiner(String nickNameJoiner) {
        this.nickNameJoiner = nickNameJoiner == null ? null : nickNameJoiner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.phone_number_joiner
     *
     * @return the value of fac_kanjia_helper.phone_number_joiner
     * @mbggenerated
     */
    public String getPhoneNumberJoiner() {
        return phoneNumberJoiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.phone_number_joiner
     *
     * @param phoneNumberJoiner the value for fac_kanjia_helper.phone_number_joiner
     * @mbggenerated
     */
    public void setPhoneNumberJoiner(String phoneNumberJoiner) {
        this.phoneNumberJoiner = phoneNumberJoiner == null ? null : phoneNumberJoiner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.token_helper
     *
     * @return the value of fac_kanjia_helper.token_helper
     * @mbggenerated
     */
    public String getTokenHelper() {
        return tokenHelper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.token_helper
     *
     * @param tokenHelper the value for fac_kanjia_helper.token_helper
     * @mbggenerated
     */
    public void setTokenHelper(String tokenHelper) {
        this.tokenHelper = tokenHelper == null ? null : tokenHelper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.nick_name_helper
     *
     * @return the value of fac_kanjia_helper.nick_name_helper
     * @mbggenerated
     */
    public String getNickNameHelper() {
        return nickNameHelper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.nick_name_helper
     *
     * @param nickNameHelper the value for fac_kanjia_helper.nick_name_helper
     * @mbggenerated
     */
    public void setNickNameHelper(String nickNameHelper) {
        this.nickNameHelper = nickNameHelper == null ? null : nickNameHelper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.phone_number_helper
     *
     * @return the value of fac_kanjia_helper.phone_number_helper
     * @mbggenerated
     */
    public String getPhoneNumberHelper() {
        return phoneNumberHelper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.phone_number_helper
     *
     * @param phoneNumberHelper the value for fac_kanjia_helper.phone_number_helper
     * @mbggenerated
     */
    public void setPhoneNumberHelper(String phoneNumberHelper) {
        this.phoneNumberHelper = phoneNumberHelper == null ? null : phoneNumberHelper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.help_price
     *
     * @return the value of fac_kanjia_helper.help_price
     * @mbggenerated
     */
    public BigDecimal getHelpPrice() {
        return helpPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.help_price
     *
     * @param helpPrice the value for fac_kanjia_helper.help_price
     * @mbggenerated
     */
    public void setHelpPrice(BigDecimal helpPrice) {
        this.helpPrice = helpPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.create_time
     *
     * @return the value of fac_kanjia_helper.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.create_time
     *
     * @param createTime the value for fac_kanjia_helper.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.update_time
     *
     * @return the value of fac_kanjia_helper.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.update_time
     *
     * @param updateTime the value for fac_kanjia_helper.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.operator_id
     *
     * @return the value of fac_kanjia_helper.operator_id
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.operator_id
     *
     * @param operatorId the value for fac_kanjia_helper.operator_id
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.operator_name
     *
     * @return the value of fac_kanjia_helper.operator_name
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.operator_name
     *
     * @param operatorName the value for fac_kanjia_helper.operator_name
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_kanjia_helper.is_deleted
     *
     * @return the value of fac_kanjia_helper.is_deleted
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_kanjia_helper.is_deleted
     *
     * @param isDeleted the value for fac_kanjia_helper.is_deleted
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}