package com.ruoyi.fac.model;

import java.util.Date;

public class FacLeaveMessageReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.message_id
     *
     * @mbggenerated
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.token_ask
     *
     * @mbggenerated
     */
    private String tokenAsk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.token_answer
     *
     * @mbggenerated
     */
    private String tokenAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.mngt_remark
     *
     * @mbggenerated
     */
    private String mngtRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_leave_message_reply.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.id
     *
     * @return the value of fac_leave_message_reply.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.id
     *
     * @param id the value for fac_leave_message_reply.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.message_id
     *
     * @return the value of fac_leave_message_reply.message_id
     *
     * @mbggenerated
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.message_id
     *
     * @param messageId the value for fac_leave_message_reply.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.token_ask
     *
     * @return the value of fac_leave_message_reply.token_ask
     *
     * @mbggenerated
     */
    public String getTokenAsk() {
        return tokenAsk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.token_ask
     *
     * @param tokenAsk the value for fac_leave_message_reply.token_ask
     *
     * @mbggenerated
     */
    public void setTokenAsk(String tokenAsk) {
        this.tokenAsk = tokenAsk == null ? null : tokenAsk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.token_answer
     *
     * @return the value of fac_leave_message_reply.token_answer
     *
     * @mbggenerated
     */
    public String getTokenAnswer() {
        return tokenAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.token_answer
     *
     * @param tokenAnswer the value for fac_leave_message_reply.token_answer
     *
     * @mbggenerated
     */
    public void setTokenAnswer(String tokenAnswer) {
        this.tokenAnswer = tokenAnswer == null ? null : tokenAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.mngt_remark
     *
     * @return the value of fac_leave_message_reply.mngt_remark
     *
     * @mbggenerated
     */
    public String getMngtRemark() {
        return mngtRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.mngt_remark
     *
     * @param mngtRemark the value for fac_leave_message_reply.mngt_remark
     *
     * @mbggenerated
     */
    public void setMngtRemark(String mngtRemark) {
        this.mngtRemark = mngtRemark == null ? null : mngtRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.create_time
     *
     * @return the value of fac_leave_message_reply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.create_time
     *
     * @param createTime the value for fac_leave_message_reply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.update_time
     *
     * @return the value of fac_leave_message_reply.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.update_time
     *
     * @param updateTime the value for fac_leave_message_reply.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.operator_id
     *
     * @return the value of fac_leave_message_reply.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.operator_id
     *
     * @param operatorId the value for fac_leave_message_reply.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.operator_name
     *
     * @return the value of fac_leave_message_reply.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.operator_name
     *
     * @param operatorName the value for fac_leave_message_reply.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_leave_message_reply.is_deleted
     *
     * @return the value of fac_leave_message_reply.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_leave_message_reply.is_deleted
     *
     * @param isDeleted the value for fac_leave_message_reply.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}