package com.ruoyi.fac.model;

import java.math.BigDecimal;
import java.util.Date;

public class FacOrderProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.prod_id
     *
     * @mbggenerated
     */
    private Long prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.prod_name
     *
     * @mbggenerated
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.prod_number
     *
     * @mbggenerated
     */
    private Short prodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.inviter_id
     *
     * @mbggenerated
     */
    private Long inviterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_order_product.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.id
     *
     * @return the value of fac_order_product.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.id
     *
     * @param id the value for fac_order_product.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.order_no
     *
     * @return the value of fac_order_product.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.order_no
     *
     * @param orderNo the value for fac_order_product.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.prod_id
     *
     * @return the value of fac_order_product.prod_id
     *
     * @mbggenerated
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.prod_id
     *
     * @param prodId the value for fac_order_product.prod_id
     *
     * @mbggenerated
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.prod_name
     *
     * @return the value of fac_order_product.prod_name
     *
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.prod_name
     *
     * @param prodName the value for fac_order_product.prod_name
     *
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.prod_number
     *
     * @return the value of fac_order_product.prod_number
     *
     * @mbggenerated
     */
    public Short getProdNumber() {
        return prodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.prod_number
     *
     * @param prodNumber the value for fac_order_product.prod_number
     *
     * @mbggenerated
     */
    public void setProdNumber(Short prodNumber) {
        this.prodNumber = prodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.inviter_id
     *
     * @return the value of fac_order_product.inviter_id
     *
     * @mbggenerated
     */
    public Long getInviterId() {
        return inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.inviter_id
     *
     * @param inviterId the value for fac_order_product.inviter_id
     *
     * @mbggenerated
     */
    public void setInviterId(Long inviterId) {
        this.inviterId = inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.price
     *
     * @return the value of fac_order_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.price
     *
     * @param price the value for fac_order_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.token
     *
     * @return the value of fac_order_product.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.token
     *
     * @param token the value for fac_order_product.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.open_id
     *
     * @return the value of fac_order_product.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.open_id
     *
     * @param openId the value for fac_order_product.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.user_id
     *
     * @return the value of fac_order_product.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.user_id
     *
     * @param userId the value for fac_order_product.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.user_name
     *
     * @return the value of fac_order_product.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.user_name
     *
     * @param userName the value for fac_order_product.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.nick_name
     *
     * @return the value of fac_order_product.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.nick_name
     *
     * @param nickName the value for fac_order_product.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.create_time
     *
     * @return the value of fac_order_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.create_time
     *
     * @param createTime the value for fac_order_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.update_time
     *
     * @return the value of fac_order_product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.update_time
     *
     * @param updateTime the value for fac_order_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.operator_id
     *
     * @return the value of fac_order_product.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.operator_id
     *
     * @param operatorId the value for fac_order_product.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.operator_name
     *
     * @return the value of fac_order_product.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.operator_name
     *
     * @param operatorName the value for fac_order_product.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_order_product.is_deleted
     *
     * @return the value of fac_order_product.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_order_product.is_deleted
     *
     * @param isDeleted the value for fac_order_product.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}